### ISSUE TITLE
Improve contrast for links

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/base_style#1]
As can be seen in e.g. the [VLO help page](https://vlo.clarin.eu/help) or any [blog post with many links](https://www.clarin.eu/blog/cmdi-12-has-arrived), hypertext links can be hard to distinguish from the other running text. Adapt the style to make them more easily distinguishable (but also look good in isolation).

**Comment by dietervu** [comment]
Currently links (from an html element) are shown in #07426e - it is too difficult to distinguish this colour from the standard body text colour (#333). Changing the link colour to #0080AA solves this issue.

**Comment by twagoo** [comment]
Is this fixed by https://github.com/clarin-eric/base_style/releases/tag/0.1.1 ?
